import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — sousChef",
  description: "The terms and conditions governing your use of sousChef.",
};

const LAST_UPDATED = "August 2026";
const CONTACT_EMAIL = "hello@souschef.app";

export default function TermsPage(): React.JSX.Element {
  return (
    <div className="mx-auto max-w-2xl px-4 py-16">
      <Link href="/" className="text-sm text-orange-500 hover:underline">
        ← Back to sousChef
      </Link>

      <h1 className="mt-6 text-3xl font-bold text-gray-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-gray-400">Last updated: {LAST_UPDATED}</p>

      <div className="mt-10 space-y-8 text-sm text-gray-700 leading-relaxed">

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">1. Acceptance of terms</h2>
          <p>
            By creating an account or using sousChef, you agree to these Terms of Service.
            If you do not agree, please do not use the service. We may update these terms from
            time to time; continued use after an update constitutes acceptance of the revised
            terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">2. The service</h2>
          <p>
            sousChef is a recipe management and cooking companion application. We provide tools
            to save and organise recipes, plan meals, manage your pantry, track fermentation
            projects, and connect with a community of home cooks. The service is provided "as
            is" and we reserve the right to modify, suspend, or discontinue any part of it at
            any time.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">3. Accounts</h2>
          <p>
            You must be at least 13 years old to create an account. You are responsible for
            maintaining the security of your account credentials. You must not share your
            account with others or create accounts on behalf of third parties without
            authorisation. We reserve the right to suspend or terminate accounts that violate
            these terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">4. Your content</h2>
          <p>
            You retain ownership of the recipes and content you create in sousChef. By making
            a recipe public or sharing it in the community, you grant other users the right to
            view and fork (copy and adapt) that recipe within the sousChef platform. You
            represent that you have the right to share any content you upload, including that
            it does not infringe third-party intellectual property rights.
          </p>
          <p className="mt-2">
            You must not upload content that is unlawful, harmful, threatening, defamatory,
            or otherwise objectionable.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">5. Recipe imports</h2>
          <p>
            sousChef allows you to import recipes from third-party websites. You are
            responsible for ensuring that your use of imported recipes complies with the
            copyright terms of the source website. sousChef is a personal organisation tool;
            it is not intended for commercial republication of third-party recipe content.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">6. AI features</h2>
          <p>
            Some features of sousChef use artificial intelligence to assist with recipe import
            and adaptation. AI-generated output may be inaccurate. You should always verify
            ingredient quantities, cooking times, and food safety information before following
            a recipe, particularly one that has been adapted or generated by AI.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">7. Acceptable use</h2>
          <p>You must not use sousChef to:</p>
          <ul className="mt-2 list-disc list-inside space-y-1 text-gray-600">
            <li>Violate any applicable laws or regulations</li>
            <li>Scrape, crawl, or extract data from the service by automated means</li>
            <li>Attempt to gain unauthorised access to any part of the service</li>
            <li>Interfere with or disrupt the service or its infrastructure</li>
            <li>Upload malicious code or content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">8. Limitation of liability</h2>
          <p>
            To the extent permitted by law, sousChef is provided without warranty of any kind.
            We are not liable for any indirect, incidental, or consequential damages arising
            from your use of the service. Our total liability to you for any claim arising from
            these terms or your use of sousChef shall not exceed the amount you have paid us
            in the 12 months preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">9. Termination</h2>
          <p>
            You may stop using sousChef and delete your account at any time via{" "}
            <strong>Settings → Danger zone</strong>. We may suspend or terminate your access
            if you breach these terms. Upon termination, your content will be deleted in
            accordance with our{" "}
            <Link href="/privacy" className="text-orange-500 hover:underline">
              Privacy Policy
            </Link>
            .
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">10. Governing law</h2>
          <p>
            These terms are governed by the laws of England and Wales. Any disputes shall be
            subject to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-gray-900 mb-2">11. Contact</h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-orange-500 hover:underline">
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </section>

      </div>
    </div>
  );
}
